/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AI_GATEWAY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ZONE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SURREALDB_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}