/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as PromptsIndexRouteImport } from './routes/prompts/index'
import { Route as PromptsPromptIdRouteImport } from './routes/prompts/$promptId'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as TasksTaskIdIndexRouteImport } from './routes/tasks/$taskId/index'
import { Route as TasksTaskIdBriefRouteImport } from './routes/tasks/$taskId/brief'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsPromptIdRoute = PromptsPromptIdRouteImport.update({
  id: '/prompts/$promptId',
  path: '/prompts/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdIndexRoute = TasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdBriefRoute = TasksTaskIdBriefRouteImport.update({
  id: '/tasks/$taskId/brief',
  path: '/tasks/$taskId/brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/prompts': typeof PromptsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/$taskId/brief': typeof TasksTaskIdBriefRoute
  '/tasks/$taskId': typeof TasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/prompts': typeof PromptsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/$taskId/brief': typeof TasksTaskIdBriefRoute
  '/tasks/$taskId': typeof TasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/prompts/': typeof PromptsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/$taskId/brief': typeof TasksTaskIdBriefRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/users'
    | '/api/chat'
    | '/prompts/$promptId'
    | '/prompts'
    | '/tasks'
    | '/tasks/$taskId/brief'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services'
    | '/users'
    | '/api/chat'
    | '/prompts/$promptId'
    | '/prompts'
    | '/tasks'
    | '/tasks/$taskId/brief'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/users'
    | '/api/chat'
    | '/prompts/$promptId'
    | '/prompts/'
    | '/tasks/'
    | '/tasks/$taskId/brief'
    | '/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRoute: typeof ServicesRoute
  UsersRoute: typeof UsersRoute
  ApiChatRoute: typeof ApiChatRoute
  PromptsPromptIdRoute: typeof PromptsPromptIdRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TasksTaskIdBriefRoute: typeof TasksTaskIdBriefRoute
  TasksTaskIdIndexRoute: typeof TasksTaskIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$promptId': {
      id: '/prompts/$promptId'
      path: '/prompts/$promptId'
      fullPath: '/prompts/$promptId'
      preLoaderRoute: typeof PromptsPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/': {
      id: '/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/brief': {
      id: '/tasks/$taskId/brief'
      path: '/tasks/$taskId/brief'
      fullPath: '/tasks/$taskId/brief'
      preLoaderRoute: typeof TasksTaskIdBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRoute: ServicesRoute,
  UsersRoute: UsersRoute,
  ApiChatRoute: ApiChatRoute,
  PromptsPromptIdRoute: PromptsPromptIdRoute,
  PromptsIndexRoute: PromptsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TasksTaskIdBriefRoute: TasksTaskIdBriefRoute,
  TasksTaskIdIndexRoute: TasksTaskIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
