/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForbiddenRouteImport } from './routes/auth/forbidden'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedServicesRouteImport } from './routes/_authed/services'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks/index'
import { Route as AuthedPromptsIndexRouteImport } from './routes/_authed/prompts/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedPromptsPromptIdRouteImport } from './routes/_authed/prompts/$promptId'
import { Route as AuthedTasksTaskIdIndexRouteImport } from './routes/_authed/tasks/$taskId/index'
import { Route as AuthedTasksTaskIdBriefRouteImport } from './routes/_authed/tasks/$taskId/brief'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForbiddenRoute = AuthForbiddenRouteImport.update({
  id: '/auth/forbidden',
  path: '/auth/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesRoute = AuthedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPromptsIndexRoute = AuthedPromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPromptsPromptIdRoute = AuthedPromptsPromptIdRouteImport.update({
  id: '/prompts/$promptId',
  path: '/prompts/$promptId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksTaskIdIndexRoute = AuthedTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksTaskIdBriefRoute = AuthedTasksTaskIdBriefRouteImport.update({
  id: '/tasks/$taskId/brief',
  path: '/tasks/$taskId/brief',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof AuthedServicesRoute
  '/users': typeof AuthedUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forbidden': typeof AuthForbiddenRoute
  '/auth/signin': typeof AuthSigninRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/prompts/$promptId': typeof AuthedPromptsPromptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/prompts': typeof AuthedPromptsIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/tasks/$taskId/brief': typeof AuthedTasksTaskIdBriefRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof AuthedServicesRoute
  '/users': typeof AuthedUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forbidden': typeof AuthForbiddenRoute
  '/auth/signin': typeof AuthSigninRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/prompts/$promptId': typeof AuthedPromptsPromptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/prompts': typeof AuthedPromptsIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/tasks/$taskId/brief': typeof AuthedTasksTaskIdBriefRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/services': typeof AuthedServicesRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forbidden': typeof AuthForbiddenRoute
  '/auth/signin': typeof AuthSigninRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/_authed/prompts/$promptId': typeof AuthedPromptsPromptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/prompts/': typeof AuthedPromptsIndexRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
  '/_authed/tasks/$taskId/brief': typeof AuthedTasksTaskIdBriefRoute
  '/_authed/tasks/$taskId/': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/users'
    | '/api/chat'
    | '/auth/forbidden'
    | '/auth/signin'
    | '/task/$taskId'
    | '/prompts/$promptId'
    | '/api/auth/$'
    | '/prompts'
    | '/tasks'
    | '/tasks/$taskId/brief'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services'
    | '/users'
    | '/api/chat'
    | '/auth/forbidden'
    | '/auth/signin'
    | '/task/$taskId'
    | '/prompts/$promptId'
    | '/api/auth/$'
    | '/prompts'
    | '/tasks'
    | '/tasks/$taskId/brief'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/services'
    | '/_authed/users'
    | '/api/chat'
    | '/auth/forbidden'
    | '/auth/signin'
    | '/task/$taskId'
    | '/_authed/prompts/$promptId'
    | '/api/auth/$'
    | '/_authed/prompts/'
    | '/_authed/tasks/'
    | '/_authed/tasks/$taskId/brief'
    | '/_authed/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  AuthForbiddenRoute: typeof AuthForbiddenRoute
  AuthSigninRoute: typeof AuthSigninRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forbidden': {
      id: '/auth/forbidden'
      path: '/auth/forbidden'
      fullPath: '/auth/forbidden'
      preLoaderRoute: typeof AuthForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services': {
      id: '/_authed/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthedServicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/prompts/': {
      id: '/_authed/prompts/'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthedPromptsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/prompts/$promptId': {
      id: '/_authed/prompts/$promptId'
      path: '/prompts/$promptId'
      fullPath: '/prompts/$promptId'
      preLoaderRoute: typeof AuthedPromptsPromptIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/': {
      id: '/_authed/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthedTasksTaskIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/brief': {
      id: '/_authed/tasks/$taskId/brief'
      path: '/tasks/$taskId/brief'
      fullPath: '/tasks/$taskId/brief'
      preLoaderRoute: typeof AuthedTasksTaskIdBriefRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedServicesRoute: typeof AuthedServicesRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedPromptsPromptIdRoute: typeof AuthedPromptsPromptIdRoute
  AuthedPromptsIndexRoute: typeof AuthedPromptsIndexRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
  AuthedTasksTaskIdBriefRoute: typeof AuthedTasksTaskIdBriefRoute
  AuthedTasksTaskIdIndexRoute: typeof AuthedTasksTaskIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedServicesRoute: AuthedServicesRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedPromptsPromptIdRoute: AuthedPromptsPromptIdRoute,
  AuthedPromptsIndexRoute: AuthedPromptsIndexRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
  AuthedTasksTaskIdBriefRoute: AuthedTasksTaskIdBriefRoute,
  AuthedTasksTaskIdIndexRoute: AuthedTasksTaskIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  AuthForbiddenRoute: AuthForbiddenRoute,
  AuthSigninRoute: AuthSigninRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
